# planingのテスト用

In [1]:
cd ../src/

/home/miyazawa/c_iwata_ws/src/crest_camp_ros/src


In [2]:
import sys
from ica_planner import Planner
import pandas as pd
from mmlda_bhmm.word_client import WordClient
from hmm_mmlda_hmm import ICA, df2list, make_obs
import numpy as np
planner = Planner()

In [3]:

obs_df = pd.read_csv("./obs_data.csv", index_col=[0,1,2], header=[0,1] )
sen_df = pd.read_csv("./sen_data.csv")
while True:
    obs, correct = make_obs(obs_df, sen_df)
    O_O = obs[0][0].reshape(1,-1) # 物体情報
    M_M = obs[1][0].reshape(1,-1) # 動作情報
    P_P = obs[2][0].reshape(1,-1) # 場所情報
    W_ALL = obs[3][0].reshape(1,-1) #言語情報 (初期状態に言語情報を使用しない場合は0で埋める)
    obs4plane = [O_O, M_M, P_P, W_ALL]
    planing_results = planner.plane(obs4plane, "リビングで箱に入れる", step_n=0)
    print (planing_results)
    print ("end")
    break

/home/miyazawa/SIGVerse/nakatomo/serket/mlda/__init__.py:56: RuntimeWarning: invalid value encountered in divide
  data[m] = (data[m].T / data[m].sum(1)).T * self.__weights[m]


[(array([  2.22074173e-04,   9.99555852e-01,   2.22074173e-04]), array([ 0.20013327,  0.20013327,  0.20013327,  0.20013327,  0.19258108,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.0075522 ,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,
        0.00022212,  0.00022212,  0.00022212,  0.00022212,  0.00022212,

In [15]:
a = np.argsort(planing_results[1][1])[::-1][:5]

In [16]:
for w in  codebook[a]:
    print w

ドア
で
を
前
開ける


In [19]:
planing_results[1][2]

array([ 0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333])

In [20]:
codebook = np.loadtxt("./codebook.txt",dtype=str)

In [29]:
planner.ica.mlda2.n_mzw4bhmm[0]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.]])

In [32]:
obs[1]

array([[2, 0, 4, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [0, 1, 1, 4, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [2, 1, 0, 7, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [2, 1, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [4, 2, 0, 4, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [3, 1, 0, 4, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 1, 1, 

In [35]:
obs_df.loc[:,"action_hist"]

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  \
episode step time                                                             
0       0    1.533107e+09  2  0  4  2  0  0  0  1  1  0   0   0   0   0   0   
        1    1.533107e+09  1  1  0  3  0  0  0  1  1  0   0   0   0   0   0   
1       0    1.533107e+09  0  1  1  4  0  0  0  1  1  0   0   0   0   0   0   
2       0    1.533107e+09  2  1  0  7  0  0  0  1  1  0   0   0   0   0   0   
        1    1.533107e+09  1  1  0  1  0  0  0  1  1  0   0   0   0   0   0   
3       0    1.533108e+09  2  1  1  2  0  0  0  1  1  0   0   0   0   0   0   
        1    1.533108e+09  4  2  0  4  0  0  0  1  1  0   0   0   0   0   0   
4       0    1.533108e+09  1  0  0  2  0  0  0  1  1  0   0   0   0   0   0   
5       0    1.533108e+09  0  1  1  1  0  0  0  1  1  0   0   0   0   0   0   
6       0    1.533108e+09  3  1  0  4  0  0  0  1  1  0   0   0   0   0   0   
        1    1.533108e+09  1  1  1  1  0  0  0  1  1  0   0   0   0   0   0   
7       0    1.533108e+09  2  1  0  0  1  1  5  1  1  0   0   0   0   0   0   
        1    1.533109e+09  2  0  2  2  0  0  0  1  1  0   0   0   0   0   0   
        2    1.533109e+09  1  1  0  3  0  0  0  1  1  0   0   0   0   0   0   
8       0    1.533109e+09  4  3  0  0  2  2  4  1  1  0   0   0   0   0   0   
        1    1.533109e+09  0  1  1  2  0  0  0  1  1  0   0   0   0   0   0   
12      0    1.533110e+09  2  1  0  3  1  1  3  1  1  0   0   0   0   0   0   
        1    1.533110e+09  2  1  0  3  0  0  0  1  1  0   0   0   0   0   0   
        2    1.533110e+09  2  1  1  2  0  0  0  1  1  0   0   0   0   0   0   
13      0    1.533110e+09  3  1  0  0  1  1  3  1  1  0   0   0   0   0   0   
        1    1.533110e+09  1  1  0  2  0  0  0  1  1  0   0   0   0   0   0   
        2    1.533110e+09  1  1  0  2  0  0  0  1  1  0   0   0   0   0   0   
14      0    1.533111e+09  1  3  0  2  1  2  2  1  1  0   0   0   0   0   0   
        1    1.533111e+09  1  1  0  6  0  0  0  1  1  0   0   0   0   0   0   
        2    1.533111e+09  1  1  0  1  0  0  0  1  1  0   0   0   0   0   0   
15      0    1.533111e+09  1  1  0  2  1  1  2  1  1  0   0   0   0   0   0   
        1    1.533111e+09  1  1  1  1  0  0  0  1  1  0   0   0   0   0   0   
17      0    1.533111e+09  1  2  0  1  1  1  3  1  1  0   0   0   0   0   0   
        1    1.533111e+09  3  1  0  4  0  0  0  1  1  0   0   0   0   0   0   
        2    1.533111e+09  1  1  0  2  0  0  0  1  1  0   0   0   0   0   0   

                           15  16  17  18  19  20  21  22  23  24  25  26  
episode step time                                                          
0       0    1.533107e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0   0   0   0   0   0   0  
1       0    1.533107e+09   0   0   0   0   0   0   0   0   0   0   0   0  
2       0    1.533107e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0   0   0   0   0   0   0  
3       0    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
4       0    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
5       0    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
6       0    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
7       0    1.533108e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533109e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        2    1.533109e+09   0   0   0   0   0   0   0   0   0   0   0   0  
8       0    1.533109e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533109e+09   0   0   0   0   0   0   0   0   0   0   0   0  
12      0    1.533110e+09   0   0   0   0   0   0   0   0   0   0   0   0  
        1    1.533110e+09   0   0   0   0   0   0   0 

In [34]:
pd.set_option('display.max_columns', 50)