# planingのテスト用

In [1]:
cd ../src/

/home/miyazawa/c_iwata_ws/src/crest_camp_ros/src


In [2]:
import sys
from ica_planner import Planner
import pandas as pd
from mmlda_bhmm.word_client import WordClient
from hmm_mmlda_hmm import ICA, df2list, make_obs
import numpy as np
planner = Planner()

In [3]:

obs_df = pd.read_csv("./obs_data.csv", index_col=[0,1,2], header=[0,1] )
sen_df = pd.read_csv("./sen_data.csv")
while True:
    obs, correct = make_obs(obs_df, sen_df)
    O_O = obs[0][0].reshape(1,-1) # 物体情報
    M_M = obs[1][0].reshape(1,-1) # 動作情報
    P_P = obs[2][0].reshape(1,-1) # 場所情報
    W_ALL = obs[3][0].reshape(1,-1) #言語情報 (初期状態に言語情報を使用しない場合は0で埋める)
    obs4plane = [O_O, M_M, P_P, W_ALL]
    planing_results = planner.plane(obs4plane, "リビングで箱に入れる", step_n=0)
    break

/home/miyazawa/SIGVerse/nakatomo/serket/mlda/__init__.py:56: RuntimeWarning: invalid value encountered in divide
  data[m] = (data[m].T / data[m].sum(1)).T * self.__weights[m]


In [4]:
codebook = np.loadtxt("./codebook.txt",dtype=str)

In [5]:
a = np.argsort(planing_results[0][3])[::-1][:5]

In [6]:
for w in  codebook[a]:
    print w

キッチン
で
ペットボトル
を
掴む


In [7]:
planing_results[1][2]

array([ 0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333])

In [8]:
for w in codebook:
    print w

キッチン
で
ペットボトル
を
掴む
リビング
箱
に
入れる
ドア
前
開ける
つかむ


In [9]:
print planner.ica.mlda2.n_mzw4bhmm[0].astype(int)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [10]:
print planner.ica.mlda1.n_mzw4bhmm[0].astype(int)

[[700   0   0]
 [  0   0 350]
 [  0 450   0]]


In [12]:
print obs[0].shape

(30, 3)


In [16]:
print obs[3].shape

(30, 200)


In [17]:
obs_df.loc[:,"action_hist"]

0  1  2  3  4  5  6  7  8  9 ...  17  18  19  20  \
episode step time                                       ...                   
0       0    1.533107e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        1    1.533107e+09  1  1  0  3  0  0  0  1  1  0 ...   0   0   0   0   
1       0    1.533107e+09  0  1  1  4  0  0  0  1  1  0 ...   0   0   0   0   
2       0    1.533107e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        1    1.533107e+09  1  1  0  1  0  0  0  1  1  0 ...   0   0   0   0   
3       0    1.533108e+09  2  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
        1    1.533108e+09  0  0  0  0  0  0  0  0  0  4 ...   1   0   0   0   
4       0    1.533108e+09  1  0  0  2  0  0  0  1  1  0 ...   0   0   0   0   
5       0    1.533108e+09  0  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
6       0    1.533108e+09  0  0  0  0  0  0  0  0  0  3 ...   1   0   0   0   
        1    1.533108e+09  1  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
7       0    1.533108e+09  0  0  0  0  0  0  0  0  0  0 ...   0   2   1   0   
        1    1.533109e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        2    1.533109e+09  1  1  0  3  0  0  0  1  1  0 ...   0   0   0   0   
8       0    1.533109e+09  0  0  0  0  0  0  0  0  0  0 ...   0   4   3   0   
        1    1.533109e+09  0  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
12      0    1.533110e+09  0  0  0  0  0  0  0  0  0  0 ...   0   2   1   0   
        1    1.533110e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        2    1.533110e+09  2  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
13      0    1.533110e+09  0  0  0  0  0  0  0  0  0  0 ...   0   3   1   0   
        1    1.533110e+09  0  0  0  0  0  0  0  0  0  1 ...   1   0   0   0   
        2    1.533110e+09  1  1  0  2  0  0  0  1  1  0 ...   0   0   0   0   
14      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   3   0   
        1    1.533111e+09  0  0  0  0  0  0  0  0  0  1 ...   1   0   0   0   
        2    1.533111e+09  1  1  0  1  0  0  0  1  1  0 ...   0   0   0   0   
15      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   1   0   
        1    1.533111e+09  1  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
17      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   2   0   
        1    1.533111e+09  0  0  0  0  0  0  0  0  0  3 ...   1   0   0   0   
        2    1.533111e+09  1  1  0  2  0  0  0  1  1  0 ...   0   0   0   0   

                           21  22  23  24  25  26  
episode step time                                  
0       0    1.533107e+09   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0  
1       0    1.533107e+09   0   0   0   0   0   0  
2       0    1.533107e+09   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0  
3       0    1.533108e+09   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0  
4       0    1.533108e+09   0   0   0   0   0   0  
5       0    1.533108e+09   0   0   0   0   0   0  
6       0    1.533108e+09   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0  
7       0    1.533108e+09   0   1   1   5   1   1  
        1    1.533109e+09   0   0   0   0   0   0  
        2    1.533109e+09   0   0   0   0   0   0  
8       0    1.533109e+09   0   2   2   4   1   1  
        1    1.533109e+09   0   0   0   0   0   0  
12      0    1.533110e+09   3   1   1   3   1   1  
        1    1.533110e+09   0   0   0   0   0   0  
        2    1.533110e+09   0   0   0   0   0   0  
13      0    1.533110e+09   0   1   1   3   1   1  
        1    1.533110e+09   0   0   0   0   0   0  
        2    1.533110e+09   0   0   0   0   0   0  
14      0    1.533111e+09   2   1   2   2   1   1  
        1    1.533111e+09   0   0   0   0   0   0  
        2    1.533111e+09   0   0   0   0   0   0  
15      0    1.533111e+09   2   1   1   2   1   1  
        1    1.533111e+09   0   0   0   0 

In [34]:
pd.set_option('display.max_columns', 50)

In [26]:
sen_df

sentence  episode  step
0    キッチンでペットボトルを掴む        0     0
1    キッチンでペットボトルを掴む        0     0
2    キッチンでペットボトルを掴む        0     0
3        リビングで箱に入れる        0     1
4        リビングで箱に入れる        0     1
5        リビングで箱に入れる        1     0
6        リビングで箱に入れる        1     0
7    キッチンでペットボトルを掴む        2     0
8    キッチンでペットボトルを掴む        2     0
9        リビングで箱に入れる        2     1
10       リビングで箱に入れる        2     1
11       リビングで箱に入れる        3     0
12       リビングで箱に入れる        3     0
13   キッチンでペットボトルを掴む        3     1
14   キッチンでペットボトルを掴む        3     1
15       リビングで箱に入れる        4     0
16       リビングで箱に入れる        5     0
17       リビングで箱に入れる        5     0
18   キッチンでペットボトルを掴む        6     0
19   キッチンでペットボトルを掴む        6     0
20       リビングで箱に入れる        6     1
21       リビングで箱に入れる        6     1
22       ドア前でドアを開ける        7     0
23       ドア前でドアを開ける        7     0
24   キッチンでペットボトルを掴む        7     1
25   キッチンでペットボトルを掴む        7     1
26       リビングで箱に入れる        7     2
27       リビングで箱に入れる        7     2
28       リビングで箱に入れる        7     2
29       ドア前でドアを開ける        8     0
..              ...      ...   ...
33       ドア前でドアを開ける       12     0
34   キッチンでペットボトルを掴む       12     1
35   キッチンでペットボトルを掴む       12     1
36       リビングで箱に入れる       12     2
37       リビングで箱に入れる       12     2
38       ドア前でドアを開ける       13     0
39       ドア前でドアを開ける       13     0
40       ドア前でドアを開ける       13     0
41   キッチンでペットボトルを掴む       13     1
42   キッチンでペットボトルを掴む       13     1
43       リビングで箱に入れる       13     2
44       ドア前でドアを開ける       14     0
45       ドア前でドアを開ける       14     0
46   キッチンでペットボトルを掴む       14     1
47   キッチンでペットボトルを掴む       14     1
48       リビングで箱に入れる       14     2
49       リビングで箱に入れる       14     2
50       ドア前でドアを開ける       15     0
51       ドア前でドアを開ける       15     0
52       ドア前でドアを開ける       15     0
53       リビングで箱に入れる       15     1
54       リビングで箱に入れる       15     1
55       リビングで箱に入れる       15     1
56       ドア前でドアを開ける       17     0
57       ドア前でドアを開ける       17     0
58   キッチンでペットボトルを掴む       17     1
59  キッチンでペットボトルをつかむ       17     1
60   キッチンでペットボトルを掴む       17     1
61       リビングで箱に入れる       17     2
62       リビングで箱に入れる       17     2

[63 rows x 3 columns]

In [30]:
for sen in obs[4]:
    print sen

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

キッチン で ペットボトル を 掴む 

キッチン で ペットボトル を 掴む 

リビング で 箱 に 入れる 

リビング で 箱 に 入れる 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

ドア 前 で ドア を 開ける 

リビング で 箱 に 入れる 



In [37]:
obs_df.loc[:,"action_hist"]

0  1  2  3  4  5  6  7  8  9 ...  17  18  19  20  \
episode step time                                       ...                   
0       0    1.533107e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        1    1.533107e+09  1  1  0  3  0  0  0  1  1  0 ...   0   0   0   0   
1       0    1.533107e+09  0  1  1  4  0  0  0  1  1  0 ...   0   0   0   0   
2       0    1.533107e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        1    1.533107e+09  1  1  0  1  0  0  0  1  1  0 ...   0   0   0   0   
3       0    1.533108e+09  2  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
        1    1.533108e+09  0  0  0  0  0  0  0  0  0  4 ...   1   0   0   0   
4       0    1.533108e+09  1  0  0  2  0  0  0  1  1  0 ...   0   0   0   0   
5       0    1.533108e+09  0  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
6       0    1.533108e+09  0  0  0  0  0  0  0  0  0  3 ...   1   0   0   0   
        1    1.533108e+09  1  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
7       0    1.533108e+09  0  0  0  0  0  0  0  0  0  0 ...   0   2   1   0   
        1    1.533109e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        2    1.533109e+09  1  1  0  3  0  0  0  1  1  0 ...   0   0   0   0   
8       0    1.533109e+09  0  0  0  0  0  0  0  0  0  0 ...   0   4   3   0   
        1    1.533109e+09  0  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
12      0    1.533110e+09  0  0  0  0  0  0  0  0  0  0 ...   0   2   1   0   
        1    1.533110e+09  0  0  0  0  0  0  0  0  0  2 ...   1   0   0   0   
        2    1.533110e+09  2  1  1  2  0  0  0  1  1  0 ...   0   0   0   0   
13      0    1.533110e+09  0  0  0  0  0  0  0  0  0  0 ...   0   3   1   0   
        1    1.533110e+09  0  0  0  0  0  0  0  0  0  1 ...   1   0   0   0   
        2    1.533110e+09  1  1  0  2  0  0  0  1  1  0 ...   0   0   0   0   
14      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   3   0   
        1    1.533111e+09  0  0  0  0  0  0  0  0  0  1 ...   1   0   0   0   
        2    1.533111e+09  1  1  0  1  0  0  0  1  1  0 ...   0   0   0   0   
15      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   1   0   
        1    1.533111e+09  1  1  1  1  0  0  0  1  1  0 ...   0   0   0   0   
17      0    1.533111e+09  0  0  0  0  0  0  0  0  0  0 ...   0   1   2   0   
        1    1.533111e+09  0  0  0  0  0  0  0  0  0  3 ...   1   0   0   0   
        2    1.533111e+09  1  1  0  2  0  0  0  1  1  0 ...   0   0   0   0   

                           21  22  23  24  25  26  
episode step time                                  
0       0    1.533107e+09   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0  
1       0    1.533107e+09   0   0   0   0   0   0  
2       0    1.533107e+09   0   0   0   0   0   0  
        1    1.533107e+09   0   0   0   0   0   0  
3       0    1.533108e+09   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0  
4       0    1.533108e+09   0   0   0   0   0   0  
5       0    1.533108e+09   0   0   0   0   0   0  
6       0    1.533108e+09   0   0   0   0   0   0  
        1    1.533108e+09   0   0   0   0   0   0  
7       0    1.533108e+09   0   1   1   5   1   1  
        1    1.533109e+09   0   0   0   0   0   0  
        2    1.533109e+09   0   0   0   0   0   0  
8       0    1.533109e+09   0   2   2   4   1   1  
        1    1.533109e+09   0   0   0   0   0   0  
12      0    1.533110e+09   3   1   1   3   1   1  
        1    1.533110e+09   0   0   0   0   0   0  
        2    1.533110e+09   0   0   0   0   0   0  
13      0    1.533110e+09   0   1   1   3   1   1  
        1    1.533110e+09   0   0   0   0   0   0  
        2    1.533110e+09   0   0   0   0   0   0  
14      0    1.533111e+09   2   1   2   2   1   1  
        1    1.533111e+09   0   0   0   0   0   0  
        2    1.533111e+09   0   0   0   0   0   0  
15      0    1.533111e+09   2   1   1   2   1   1  
        1    1.533111e+09   0   0   0   0 

In [47]:
type(obs[0][0][0])

numpy.int64

In [44]:
type(obs[1][0][1])

numpy.int64