# planingのテスト用

In [1]:
cd ../src/

/home/miyazawa/c_iwata_ws/src/crest_camp_ros/src


In [2]:
import sys
from ica_planner import Planner
import pandas as pd
from mmlda_bhmm.word_client import WordClient
from hmm_mmlda_hmm import ICA, df2list, make_obs
import numpy as np

In [3]:
planner = Planner()

In [4]:
ls module007_mlda/004

Pdz.txt  Pmdw[0].txt  Pmdw[1].txt  model.pickle


In [7]:
np.loadtxt( "module007_mlda/004/Pmdw[0].txt" )

array([[ 0.00350418,  0.00353153,  0.00284782,  0.00493998,  0.00213675,
         0.00213675,  0.00213675,  0.00366827,  0.00366827,  0.2137582 ,
         0.08804249,  0.06918513,  0.36042652,  0.00213675,  0.00213675,
         0.00213675,  0.10270932,  0.10270932,  0.00355551,  0.00336078,
         0.00213675,  0.00302695,  0.00291568,  0.00302695,  0.00450135,
         0.00283222,  0.00283222],
       [ 0.13951328,  0.14227494,  0.07323324,  0.28450085,  0.00142987,
         0.00142987,  0.00142987,  0.15608328,  0.15608328,  0.00354568,
         0.00228876,  0.00210023,  0.00501208,  0.00142987,  0.00142987,
         0.00142987,  0.0024354 ,  0.0024354 ,  0.00286254,  0.0026659 ,
         0.00142987,  0.0023288 ,  0.00221644,  0.0023288 ,  0.00381765,
         0.00213216,  0.00213216],
       [ 0.13951328,  0.14227494,  0.07323324,  0.28450085,  0.00142987,
         0.00142987,  0.00142987,  0.15608328,  0.15608328,  0.00354568,
         0.00228876,  0.00210023,  0.00501208,  0.0014

In [7]:
planner.ica.mlda2.n_mzw4bhmm

In [11]:
planner.ica.mlda2._MLDA__n_mzw

[array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  

In [9]:

obs_df = pd.read_csv("./obs_data.csv", index_col=[0,1,2], header=[0,1] )
sen_df = pd.read_csv("./sen_data.csv")
while True:
    obs, correct = make_obs(obs_df, sen_df)
    O_O = obs[0][0].reshape(1,-1) # 物体情報
    M_M = obs[1][0].reshape(1,-1) # 動作情報
    P_P = obs[2][0].reshape(1,-1) # 場所情報
    W_ALL = obs[3][0].reshape(1,-1) #言語情報 (初期状態に言語情報を使用しない場合は0で埋める)
    obs4plane = [O_O, M_M, P_P, W_ALL]
    planing_results = planner.plane(obs4plane, "リビングで箱に入れる", step_n=0)
    break

/home/miyazawa/SIGVerse/nakatomo/serket/mlda/__init__.py:56: RuntimeWarning: invalid value encountered in divide
  data[m] = (data[m].T / data[m].sum(1).astype(float)).T * self.__weights[m]


In [11]:
codebook = np.loadtxt("./codebook.txt",dtype=str)

In [12]:
a = np.argsort(planing_results[0][3])[::-1][:5]

In [13]:
for w in  codebook[a]:
    print w

キッチン
で
ペットボトル
を
掴む


In [14]:
planing_results[1][2]

array([ 0.14723032,  0.15014577,  0.07725948,  0.30029155,  0.00145773,
        0.00145773,  0.00145773,  0.16472303,  0.16472303,  0.00145773,
        0.00145773,  0.00145773,  0.00145773,  0.00145773,  0.00145773,
        0.00145773,  0.00145773,  0.00145773,  0.00145773,  0.00145773,
        0.00145773,  0.00145773,  0.00145773,  0.00145773,  0.00145773,
        0.00145773,  0.00145773])

In [10]:
print planner.ica.mlda1.n_mzw4bhmm[0].astype(int)

[[700   0   0]
 [  0   0 350]
 [  0 450   0]]


In [12]:
print obs[0].shape

(30, 3)


In [16]:
print obs[3].shape

(30, 200)


In [34]:
pd.set_option('display.max_columns', 50)